### ISSUE TITLE
Too many arguments

### ISSUE THREAD

**Issue by unkn0wn107** [akhellad/Minishell#3]
@akhellad est-ce qu'il suffit de print `<ArgName> : No such file or directory` pour resoudre ca ?

```
Minishell on  master [?] 
❯ ./minishell s
Too many arguments

Minishell on  master [?] 
❯ sh s
sh: s: No such file or directory
```

**Comment by akhellad** [comment]
on est pas sensé prendre d'argument c'est écrit dans la consigne, le bash peut sans doute en prendre a son lancement mais vu que nous non je trouvais ca logique de mettre cette erreur, si tu trouve que ce serais mieux de mettre la meme erreur oui il faut juste que t'affiche argv[1]: no such file or directory
